"""Public package exports for llm_batch_annotate."""

from __future__ import annotations

from ._version import __version__
from .artifacts.naming import (
    ARTIFACT_REGISTRY,
    ArtifactDefinition,
    artifact_path,
    artifact_ref,
    artifact_refs_for_run,
    artifact_relative_path,
    get_artifact_definition,
    run_directory,
)
from .artifacts.local import LocalArtifactStore
from .builders import (
    BaseBuilder,
    ProgrammaticBuilderBase,
    PromptAssetBundle,
    SimpleTemplateBuilder,
    load_prompt_asset_text,
    load_prompt_assets,
    resolve_prompt_asset_path,
)
from .configs.models import (
    ArtifactStoreConfig,
    ArtifactStoreSelectionConfig,
    BaseProviderConfig,
    GenericProviderConfig,
    GroupingConfig,
    OpenAIBatchConfig,
    OutputConfig,
    PromptAssetsConfig,
    ProviderConfig,
    ProviderSelectionConfig,
    RetryPolicyConfig,
    RunConfig,
    RunMetadataConfig,
    SourceInputConfig,
)
from .contracts.base import ArtifactStore, BaseMessageBuilder, BaseParser, BaseTask, ExecutionProvider
from .contracts.records import (
    AnnotationRecord,
    ArtifactRef,
    ComponentRef,
    ExecutionHandle,
    FailureRecord,
    GroupRecord,
    GroupMembershipRecord,
    ParsedRequestRecord,
    ProviderCapabilities,
    RawErrorRecord,
    RawOutputRecord,
    RawResultRecord,
    RequestRecord,
    UnitRecord,
)
from .execution import (
    ExecutionProviderBase,
    OpenAIBatchProvider,
    OpenAIBatchProviderError,
    SUCCESSFUL_EXECUTION_STATUSES,
    TERMINAL_EXECUTION_STATUSES,
    is_successful_execution_status,
    is_terminal_execution_status,
    normalize_execution_status,
)
from .enums import (
    ArtifactFormat,
    ArtifactKind,
    ArtifactStoreKind,
    ExecutionStatus,
    FailureKind,
    GroupingStrategy,
    ProviderKind,
    RunStatus,
    SourceFormat,
    TaskKind,
)
from .manifests.models import (
    ComponentIdentitySummary,
    GroupingSummary,
    InputSummary,
    LineageSummary,
    ParseSummary,
    RunManifest,
    ValidationSummary,
)
from .orchestration import OfflineTaskPipeline, OfflineTaskPipelineResult, TaskOrchestrator, TaskRunState, default_run_id
from .parsers import BaseOutputParser, StructuredOutputParser
from .tasks import ComposedTaskBase, GroupedTaskBase, SingleTaskBase
from .grouping.fixed_size import build_group_memberships, membership_map, plan_fixed_size_groups
from .units.materialization import derive_unit_id, materialize_units, validate_unique_unit_ids
from .validation.coverage import CoverageValidationResult, coverage_failures, validate_coverage, validate_group_coverage

__all__ = [
    "ARTIFACT_REGISTRY",
    "AnnotationRecord",
    "ArtifactDefinition",
    "ArtifactFormat",
    "ArtifactKind",
    "ArtifactRef",
    "ArtifactStore",
    "LocalArtifactStore",
    "ArtifactStoreConfig",
    "ArtifactStoreKind",
    "ArtifactStoreSelectionConfig",
    "BaseBuilder",
    "BaseMessageBuilder",
    "BaseOutputParser",
    "BaseParser",
    "BaseProviderConfig",
    "BaseTask",
    "ComposedTaskBase",
    "ComponentIdentitySummary",
    "ComponentRef",
    "ExecutionHandle",
    "ExecutionProvider",
    "ExecutionProviderBase",
    "ExecutionStatus",
    "FailureKind",
    "FailureRecord",
    "GenericProviderConfig",
    "GroupRecord",
    "GroupMembershipRecord",
    "GroupingConfig",
    "GroupingStrategy",
    "GroupingSummary",
    "GroupedTaskBase",
    "InputSummary",
    "LineageSummary",
    "OfflineTaskPipeline",
    "OfflineTaskPipelineResult",
    "OpenAIBatchConfig",
    "OpenAIBatchProvider",
    "OpenAIBatchProviderError",
    "OutputConfig",
    "ParseSummary",
    "ParsedRequestRecord",
    "ProgrammaticBuilderBase",
    "PromptAssetBundle",
    "PromptAssetsConfig",
    "ProviderCapabilities",
    "ProviderConfig",
    "ProviderKind",
    "ProviderSelectionConfig",
    "RawErrorRecord",
    "RawOutputRecord",
    "RawResultRecord",
    "RequestRecord",
    "RetryPolicyConfig",
    "RunConfig",
    "RunManifest",
    "RunMetadataConfig",
    "RunStatus",
    "SingleTaskBase",
    "SimpleTemplateBuilder",
    "SourceFormat",
    "SourceInputConfig",
    "StructuredOutputParser",
    "SUCCESSFUL_EXECUTION_STATUSES",
    "TaskKind",
    "TaskOrchestrator",
    "TaskRunState",
    "TERMINAL_EXECUTION_STATUSES",
    "UnitRecord",
    "ValidationSummary",
    "CoverageValidationResult",
    "artifact_path",
    "artifact_ref",
    "artifact_refs_for_run",
    "artifact_relative_path",
    "build_group_memberships",
    "coverage_failures",
    "default_run_id",
    "derive_unit_id",
    "get_artifact_definition",
    "load_prompt_asset_text",
    "load_prompt_assets",
    "materialize_units",
    "membership_map",
    "normalize_execution_status",
    "plan_fixed_size_groups",
    "resolve_prompt_asset_path",
    "run_directory",
    "is_successful_execution_status",
    "is_terminal_execution_status",
    "validate_coverage",
    "validate_group_coverage",
    "validate_unique_unit_ids",
    "__version__",
]
